### ISSUE TITLE
Which version of Python?

### ISSUE THREAD

**Issue by Brock-Wood** [SylloProject/ai_miner#9]
## Expected Behavior

All devs using the same python version.

## Current Behavior

Jordan started coding, but not sure which version of python he was using. 

## Possible Solution

Python 3.6 

## Context

Starting to code, just want to make sure that we all use the same version and keep our code compatible.

**Comment by Brock-Wood** [comment]
@LegitStack I think that we should use something like lore to keep track of dependencies -- https://tech.instacart.com/freezing-pythons-dependency-hell-in-2018-f1076d625241

**Comment by Brock-Wood** [comment]
Looks like the latest stable release of Python is 3.7

**Comment by LegitStack** [comment]
I'm on 3.6.4 I'm happy to use whatever you'd like for managing dependencies. Conda has virtual environments we could use, but I've never shared them across computers before, I've always just used them alone

**Comment by Brock-Wood** [comment]
@LegitStack I take back wanting to use lore. I looked into it further, not the right tool.

**Comment by Brock-Wood** [comment]
@LegitStack I'm happy to use 3.6.4.

**Comment by Brock-Wood** [comment]
I have not used conda before. I am used to using virtualenv on my own projects but not sharing them across computers. 

How easy is it to use Conda?

**Comment by LegitStack** [comment]
@Brock-Wood easy, for instance one of us can make the environment, export it to a file, then the other can import it, we can even keep the file in the repo itself and update it accordingly. https://conda.io/docs/commands/env/conda-env-export.html

**Comment by Brock-Wood** [comment]
Yeah, it reminds me of Vagrant minus the actual VM.

**Comment by Brock-Wood** [comment]
We decided to go with 3.7.
